#!/usr/bin/env python3
"""Generate navigable documentation indexes and validate tracked local links."""
from __future__ import annotations

import argparse
from collections import Counter
import html
import json
import posixpath
from pathlib import Path
import re
import subprocess
import sys
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- Generated by scripts/documentation.py; do not edit by hand. -->"
SPECIAL = {"README.md", "AGENTS.md", "CLAUDE.md", "GEMINI.md"}
SECTIONS = {
    "guides": ("Operator guides", "Installation, authentication, safety, and operational runbooks."),
    "reference": ("Reference", "CLI, REST, MCP, configuration, integration, and storage contracts. Read each contract's implementation status."),
    "development": ("Development", "Build, test, release, plugin, and repository maintenance guidance."),
    "architecture": ("Architecture", "The current overview, architecture decisions, designs, and specifications. A design or specification does not prove implementation."),
    "history": ("History", "Preserved plans, research, reviews, reports, and session evidence. These describe their recorded point in time, not current operational instructions."),
}
NAMES = {"mcp": "MCP", "repo": "Repository maintenance", "plugins": "Plugins", "stack": "Technology stack", "upstream": "External integrations", "raycast": "Legacy Raycast placeholders", "internal": "Internal research", "superpowers": "Superpowers planning records"}
INLINE_LINK = re.compile(r"\[[^\]]*\]\(\s*(?P<target><[^>\n]+>|[^\s)]+)(?:\s+[^)\n]*)?\)")
REFERENCE_LINK = re.compile(r"(?m)^ {0,3}\[[^\]\n]+\]:\s*(?P<target><[^>\n]+>|\S+)")
HTML_LINK = re.compile(r"(?:href|src)=[\"'](?P<target>[^\"']+)[\"']", re.IGNORECASE)


def tracked_files(root: Path) -> list[str]:
    raw = subprocess.check_output(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"], cwd=root
    )
    return sorted({name for name in raw.decode().split("\0") if name and (root / name).is_file()})


def prose(text: str) -> str:
    """Mask code fences/comments without changing line offsets."""
    lines = text.splitlines(keepends=True)
    result = []
    fence = None
    for line in lines:
        match = re.match(r"^\s{0,3}(\x60{3,}|~{3,})", line)
        if match:
            token = match.group(1)
            if fence is None:
                fence = token
            elif token[0] == fence[0] and len(token) >= len(fence):
                fence = None
            result.append(re.sub(r"[^\r\n]", " ", line))
        elif fence is not None:
            result.append(re.sub(r"[^\r\n]", " ", line))
        else:
            result.append(line)
    return re.sub(r"<!--.*?-->", lambda match: re.sub(r"[^\r\n]", " ", match.group()), "".join(result), flags=re.DOTALL)


def links(text: str):
    body = prose(text)
    body = re.sub(r"(\x60+)([^\x60\n]*?)\1", lambda match: " " * len(match.group()), body)
    for pattern in (INLINE_LINK, REFERENCE_LINK, HTML_LINK):
        for match in pattern.finditer(body):
            target = match.group("target").strip("<>")
            yield body.count("\n", 0, match.start()) + 1, html.unescape(target)


def slug(heading: str) -> str:
    heading = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", heading)
    heading = re.sub(r"<[^>]*>", "", heading)
    heading = html.unescape(heading).strip().lower()
    heading = re.sub(r"[^\w\- ]", "", heading)
    return heading.replace(" ", "-")


def anchors(text: str) -> set[str]:
    body = prose(text)
    found = set(re.findall(r"(?:id|name)=[\"']([^\"']+)[\"']", body))
    seen = Counter()
    for match in re.finditer(r"(?m)^ {0,3}#{1,6}\s+(.+?)(?:\s+#+)?\s*$", body):
        value = slug(match.group(1))
        count = seen[value]
        seen[value] += 1
        found.add(value if count == 0 else f"{value}-{count}")
    return found


def title(root: Path, name: str) -> str:
    if name.endswith(".md"):
        match = re.search(r"(?m)^# (.+)$", prose((root / name).read_text()))
        if match:
            return match.group(1).replace("[", "").replace("]", "").replace("|", "/")
    return Path(name).name


def directory_title(directory: str) -> str:
    name = directory.rsplit("/", 1)[-1]
    return SECTIONS.get(name, (NAMES.get(name, name.replace("-", " ").capitalize()), ""))[0]


def index_contents(root: Path, files: list[str]) -> dict[str, str]:
    docs = [p for p in files if p.startswith("docs/") and Path(p).name != "README.md"]
    directories = set()
    for name in docs:
        parent = posixpath.dirname(name)
        while parent != "docs":
            directories.add(parent)
            parent = posixpath.dirname(parent)
    generated = {}
    for directory in sorted(directories):
        heading = directory_title(directory)
        category = directory.split("/")[1]
        intro = SECTIONS[category][1]
        children = sorted(d for d in directories if posixpath.dirname(d) == directory)
        entries = sorted(p for p in docs if posixpath.dirname(p) == directory and Path(p).name not in {"CLAUDE.md", "GEMINI.md"})
        lines = [MARKER, "", f"# {heading}", "", intro, "", "[Documentation home](" + posixpath.relpath("docs/README.md", directory) + ") · [Parent section](../README.md)", ""]
        if children:
            lines += ["## Sections", ""]
            for child in children:
                lines.append(f"- [{directory_title(child)}]({posixpath.basename(child)}/README.md)")
            lines.append("")
        if entries:
            lines += ["## Documents and artifacts", ""]
            for name in entries:
                label = title(root, name)
                suffix = "" if name.endswith(".md") else f" ({Path(name).suffix.removeprefix('.')})"
                if name.startswith("docs/history/raycast/") and not (root / name).read_bytes():
                    suffix += " · empty historical placeholder, not a runnable integration"
                lines.append(f"- [{label}]({posixpath.basename(name)}){suffix}")
            lines.append("")
        generated[directory + "/README.md"] = "\n".join(lines)
    return generated


def write_indexes(root: Path, check: bool) -> list[str]:
    issues = []
    files = tracked_files(root)
    expected = index_contents(root, files)
    for name, content in expected.items():
        path = root / name
        if path.is_symlink():
            issues.append(f"generated index is a symlink: {name}")
            continue
        data = content.encode()
        if path.exists() and path.read_bytes() == data:
            continue
        if path.exists() and MARKER not in path.read_text():
            issues.append(f"refusing to overwrite authored index: {name}")
            continue
        if check:
            issues.append(f"stale or missing generated index: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for name in files:
        if name.startswith("docs/") and name.endswith("/README.md") and name not in expected and name != "docs/README.md":
            if MARKER in (root / name).read_text():
                issues.append(f"orphan generated index; review before removing: {name}")
    return issues


def audit(root: Path, files: list[str] | None = None) -> dict:
    files = tracked_files(root) if files is None else files
    known = set(files)
    directories = {str(parent) for name in files for parent in Path(name).parents if str(parent) != "."}
    folded = {}
    errors = []
    empty_history = []
    checked_links = 0
    external_links = 0
    cache = {}
    docs = [p for p in files if p.startswith("docs/")]
    for name in docs:
        if name.casefold() in folded:
            errors.append({"file": name, "kind": "case-collision", "target": folded[name.casefold()]})
        folded[name.casefold()] = name
        parts = name.split("/")
        if len(parts) == 2 and name != "docs/README.md":
            errors.append({"file": name, "kind": "flat-root-document"})
        if len(parts) > 2 and parts[1] not in SECTIONS:
            errors.append({"file": name, "kind": "unknown-section"})
        if any(not re.fullmatch(r"[a-z0-9][a-z0-9-]*", p) for p in parts[1:-1]):
            errors.append({"file": name, "kind": "directory-casing"})
        if parts[-1] not in SPECIAL and not re.fullmatch(r"[a-z0-9][a-z0-9.-]*", parts[-1]):
            errors.append({"file": name, "kind": "filename-casing"})
        if not (root / name).read_bytes():
            if name.startswith("docs/history/"):
                empty_history.append(name)
            else:
                errors.append({"file": name, "kind": "empty-current-document"})
    markdown = [p for p in files if p.endswith(".md") and not (root / p).is_symlink()]
    for name in markdown:
        # The npm README is intentionally byte-identical to the root README.
        base = "README.md" if name == "packages/cortex-rmcp/README.md" else name
        for line, link in links((root / name).read_text()):
            parsed = urlsplit(link)
            if parsed.scheme or parsed.netloc:
                external_links += 1
                continue
            target = unquote(parsed.path)
            if target.startswith("/") or any(c in target for c in ("$", "{", "*")):
                continue
            resolved = posixpath.normpath(posixpath.join(posixpath.dirname(base), target)) if target else base
            if resolved.startswith("../"):
                continue
            checked_links += 1
            if resolved not in known and resolved not in directories:
                errors.append({"file": name, "line": line, "kind": "missing-target", "target": link, "resolved": resolved})
                continue
            fragment = unquote(parsed.fragment)
            if fragment and resolved.endswith(".md") and not re.fullmatch(r"L\d+(?:-L\d+)?", fragment):
                if resolved not in cache:
                    cache[resolved] = anchors((root / resolved).read_text())
                if fragment not in cache[resolved]:
                    errors.append({"file": name, "line": line, "kind": "missing-anchor", "target": link, "resolved": resolved})
    return {"documents": len(docs), "markdown_files": len(markdown), "local_links": checked_links,
            "external_links_not_fetched": external_links, "empty_historical_artifacts": empty_history,
            "errors": errors}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check indexes and links without modifying tracked files")
    parser.add_argument("--audit", action="store_true", help="report structure/links without generating indexes")
    parser.add_argument("--json", action="store_true", help="print the full audit as JSON")
    args = parser.parse_args()
    index_errors = [] if args.audit else write_indexes(ROOT, args.check)
    report = audit(ROOT)
    report["errors"].extend({"kind": "index-drift", "detail": issue} for issue in index_errors)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for issue in report["errors"]:
            print(json.dumps(issue), file=sys.stderr)
        print(f"Documentation: {report['documents']} files, {report['local_links']} local links, {len(report['errors'])} errors")
    return 1 if report["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
